In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("Rio de Janeiro sin atipicos 2.csv")
df.head(5)

Unnamed: 0        id  host_response_rate  host_acceptance_rate  \
0           0  280625.0                 1.0                  0.88   
1           1  280765.0                 1.0                  0.90   
2           2  281304.0                 1.0                  0.73   
3           3  281459.0                 1.0                  0.97   
4           4  282071.0                 1.0                  0.67   

   host_listings_count  host_total_listings_count  accommodates  bathrooms  \
0                 12.0                       14.0           2.0        2.0   
1                  3.0                        5.0           2.0        1.0   
2                 11.0                       12.0           4.0        1.0   
3                  1.0                        2.0           4.0        2.0   
4                  1.0                        2.0           2.0        1.0   

   bedrooms  beds  ...         property_type        room_type  bathrooms_text  \
0       1.0   1.0  ...  Private room in home     Private room  2 shared baths   
1       0.0   4.0  ...    Entire rental unit  Entire home/apt          1 bath   
2       1.0   1.0  ...    Entire rental unit  Entire home/apt          1 bath   
3       2.0   2.0  ...    Entire rental unit  Entire home/apt         2 baths   
4       1.0   1.0  ...    Entire rental unit  Entire home/apt          1 bath   

                                           amenities  calendar_updated  \
0  ["Host greets you", "Dishes and silverware", "...   SIN INFORMACION   
1  ["Stove", "Cooking basics", "Refrigerator", "D...   SIN INFORMACION   
2  ["Host greets you", "Dishes and silverware", "...   SIN INFORMACION   
3  ["Baking sheet", "Dishes and silverware", "Fre...   SIN INFORMACION   
4  ["Air conditioning", "TV with standard cable",...   SIN INFORMACION   

   has_availability  calendar_last_scraped  last_review          license  \
0                 t             25/09/2024   01/09/2024  SIN INFORMACION   
1                 t             25/09/2024   03/10/2019  SIN INFORMACION   
2                 t             26/09/2024   31/07/2024  SIN INFORMACION   
3                 t             25/09/2024   16/09/2024  SIN INFORMACION   
4                 t             25/09/2024   13/02/2024  SIN INFORMACION   

   instant_bookable  
0                 f  
1                 f  
2                 f  
3                 f  
4                 f  

[5 rows x 51 columns]

In [3]:
df= df.drop(['Unnamed: 0'], axis=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36967 entries, 0 to 36966
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   id                           36967 non-null  float64
 1   host_response_rate           36967 non-null  float64
 2   host_acceptance_rate         36967 non-null  float64
 3   host_listings_count          36967 non-null  float64
 4   host_total_listings_count    36967 non-null  float64
 5   accommodates                 36967 non-null  float64
 6   bathrooms                    36967 non-null  float64
 7   bedrooms                     36967 non-null  float64
 8   beds                         36967 non-null  float64
 9   price                        36967 non-null  float64
 10  minimum_nights               36967 non-null  float64
 11  maximum_nights               36967 non-null  float64
 12  availability_30              36967 non-null  int64  
 13  availability_60 

In [6]:
valores_nulos=df.isnull().sum()
valores_nulos

id                             0
host_response_rate             0
host_acceptance_rate           0
host_listings_count            0
host_total_listings_count      0
accommodates                   0
bathrooms                      0
bedrooms                       0
beds                           0
price                          0
minimum_nights                 0
maximum_nights                 0
availability_30                0
availability_60                0
availability_365               0
number_of_reviews              0
number_of_reviews_ltm          0
number_of_reviews_l30d         0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
reviews_per_month              0
last_scraped                   0
name                           0
description                    0
neighborhood_overview          0
picture_ur

In [8]:
# Convertir host_response_time a binario
df["host_response_time"] = df["host_response_time"].replace({
    "within an hour": "Rápido",
    "within a few hours": "Rápido",
    "within a day": "Lento",
    "a few days or more": "Lento",
    "SIN INFORMACION": "Lento"
})

# Verificar que la conversión fue correcta
print(df["host_response_time"].value_counts())

host_response_time
Rápido    25363
Lento     11604
Name: count, dtype: int64


In [10]:
df["host_is_superhost"] = df["host_is_superhost"].replace({"t": 1, "f": 0})
df["host_is_superhost"] = df["host_is_superhost"].replace({"SIN INFORMACION": 0})

C:\Users\angie\AppData\Local\Temp\ipykernel_16352\1378006797.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_is_superhost"] = df["host_is_superhost"].replace({"SIN INFORMACION": 0})


In [11]:
vars_indep=df[['host_acceptance_rate', 'host_is_superhost', 'number_of_reviews']]
var_dep=df['host_response_time']

In [12]:
X=vars_indep
y=var_dep

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [14]:
escalar=StandardScaler()

In [15]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [16]:
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

In [17]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred=algoritmo.predict(X_test)
y_pred

array(['Rápido', 'Lento', 'Rápido', ..., 'Rápido', 'Rápido', 'Rápido'],
      dtype=object)

In [19]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[ 418 3039]
 [ 663 6971]]


In [23]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="Rápido")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.6964035964035964


In [24]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.6662158506897484


In [26]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Rápido")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9131516898087503


In [30]:
df["host_is_superhost"] = df["host_is_superhost"].replace({1:"t", 0:"f"})

In [31]:
vars_indep=df[['host_response_rate', 'host_acceptance_rate', 'host_total_listings_count']]
var_dep=df['host_is_superhost']

X=vars_indep
y=var_dep

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[7475  265]
 [3014  337]]


In [35]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="f")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.7126513490323195


In [36]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.70435488233703


In [37]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9657622739018088


In [39]:
df["room_type"] = df["room_type"].replace({"Entire home/apt": 0, "Private room": 1, "Hotel room":2, "Shared room":3})

C:\Users\angie\AppData\Local\Temp\ipykernel_16352\1760127900.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["room_type"] = df["room_type"].replace({"Entire home/apt": 0, "Private room": 1, "Hotel room":2, "Shared room":3})


In [40]:
df["beds"] = df["beds"].replace({
    0: "De 0 a 3 camas",
    1: "De 0 a 3 camas",
    2: "De 0 a 3 camas",
    2.1: "De 0 a 3 camas",
    3: "De 0 a 3 camas",
    4: "De 4 a 6 camas",
    5: "De 4 a 6 camas",
    6: "De 4 a 6 camas"

})

# Verificar que la conversión fue correcta
print(df["beds"].value_counts())

beds
De 0 a 3 camas    31669
De 4 a 6 camas     5298
Name: count, dtype: int64


In [42]:
vars_indep=df[['accommodates', 'bedrooms', 'room_type']]
var_dep=df['beds']

X=vars_indep
y=var_dep

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['De 0 a 3 camas', 'De 0 a 3 camas', 'De 0 a 3 camas', ...,
       'De 0 a 3 camas', 'De 0 a 3 camas', 'De 0 a 3 camas'], dtype=object)

In [44]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[9248  216]
 [1282  345]]


In [46]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="De 0 a 3 camas")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8782526115859449


In [47]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8649355333153007


In [48]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="De 0 a 3 camas")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9771766694843618


In [49]:
df["host_is_superhost"] = df["host_is_superhost"].replace({"t": 1, "f": 0})
df["host_verifications"] = df["host_verifications"].replace({
    "[]": 0, 
    "['phone']": 1, 
    "['email']": 2, 
    "['phone', 'work_email']": 3,
    "['email', 'work_email']": 4,
    "['email', 'phone']": 5,
    "['email', 'phone', 'work_email']": 6
})

C:\Users\angie\AppData\Local\Temp\ipykernel_16352\1819986426.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_is_superhost"] = df["host_is_superhost"].replace({"t": 1, "f": 0})
C:\Users\angie\AppData\Local\Temp\ipykernel_16352\1819986426.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_verifications"] = df["host_verifications"].replace({


In [50]:
vars_indep=df[['host_listings_count', 'host_verifications', 'host_is_superhost']]
var_dep=df['host_has_profile_pic']

X=vars_indep
y=var_dep

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [52]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[    0   349]
 [    0 10742]]


In [55]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="t")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.9685330448111081


In [56]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.9685330448111081


In [58]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="t")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [59]:
vars_indep=df[['host_is_superhost', 'review_scores_communication', 'review_scores_rating']]
var_dep=df['host_identity_verified']

X=vars_indep
y=var_dep

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [61]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[   0 1815]
 [   0 9276]]


In [63]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="t")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8363538003786855


In [64]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8363538003786855


In [65]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="t")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [3]:
df["property_type"] = df["property_type"].replace({
    "Private room in home": 1,
    "Entire rental unit": 2,
    "Entire condo": 3,
    "Entire loft": 4,
    "Entire home": 5,
    "Private room in rental unit": 6,
    "Private room in townhouse": 7,
    "Private room in bed and breakfast": 8,
    "Private room in condo": 9,
    "Entire guesthouse": 10,
    "Earthen home": 11,
    "Entire townhouse": 12,
    "Shared room in rental unit": 13,
    "Entire guest suite": 14,
    "Entire serviced apartment": 15,
    "Private room in treehouse": 16,
    "Private room in guesthouse": 17,
    "Private room in hostel": 18,
    "Entire bungalow": 19,
    "Room in boutique hotel": 20,
    "Private room in earthen home": 21,
    "Shared room in home": 22,
    "Entire chalet": 23,
    "Entire cottage": 24,
    "Entire place": 25,
    "Private room in serviced apartment": 26,
    "Room in aparthotel": 27,
    "Treehouse": 28,
    "Shared room in townhouse": 29,
    "Entire villa": 30,
    "Room in serviced apartment": 31,
    "Ranch": 32,
    "Entire vacation home": 33,
    "Private room in casa particular": 34,
    "Private room in villa": 35,
    "Shared room in bed and breakfast": 36,
    "Shared room": 37,
    "Private room in tiny home": 38,
    "Private room": 39,
    "Private room in loft": 40,
    "Shared room in condo": 41,
    "Boat": 42,
    "Tiny home": 43,
    "Private room in guest suite": 44,
    "Shared room in guesthouse": 45,
    "Room in bed and breakfast": 46,
    "Room in hostel": 47,
    "Farm stay": 48,
    "Entire bed and breakfast": 49,
    "Entire cabin": 50,
    "Private room in castle": 51,
    "Casa particular": 52,
    "Shared room in loft": 53,
    "Shared room in hostel": 54,
    "Private room in floor": 55,
    "Room in hotel": 56,
    "Private room in bungalow": 57,
    "Private room in farm stay": 58,
    "Private room in chalet": 59,
    "Shared room in serviced apartment": 60,
    "Private room in boat": 61,
    "Shared room in casa particular": 62,
    "Hut": 63,
    "Shared room in guest suite": 64,
    "Camper/RV": 65,
    "Shared room in earthen home": 66,
    "Dome": 67,
    "Private room in nature lodge": 68,
    "Shared room in tiny home": 69,
    "Private room in cottage": 70,
    "Shared room in vacation home": 71,
    "Private room in resort": 72,
    "Campsite": 73,
    "Shared room in hotel": 74,
    "Private room in vacation home": 75,
    "Shared room in tent": 76,
    "Shared room in nature lodge": 77,
    "Castle": 78,
    "Private room in tent": 79,
    "Shipping container": 80,
    "Private room in tower": 81,
    "Houseboat": 82
})


C:\Users\angie\AppData\Local\Temp\ipykernel_3896\524212660.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["property_type"] = df["property_type"].replace({


In [5]:
df["room_type"] = df["room_type"].replace({
    "Entire home/apt":"Entire home/apt ",
    "Private room":"No Entire home/apt",
    "Shared room":"No Entire home/apt",
    "Hotel room":"No Entire home/apt"
})

print(df["room_type"].value_counts())

room_type
Entire home/apt       29079
No Entire home/apt     7888
Name: count, dtype: int64


In [6]:
vars_indep=df[['property_type', 'accommodates', 'price']]
var_dep=df['room_type']

X=vars_indep
y=var_dep

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['No Entire home/apt', 'Entire home/apt ', 'Entire home/apt ', ...,
       'Entire home/apt ', 'No Entire home/apt', 'Entire home/apt '],
      dtype=object)

In [8]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[8437  275]
 [1149 1230]]


In [11]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="No Entire home/apt")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8172757475083057


In [12]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8716076097736903


In [13]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="No Entire home/apt")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.5170239596469105


In [23]:
df["host_is_superhost"] = df["host_is_superhost"].replace({"SIN INFORMACION":'f'})

In [24]:
vars_indep=df[['price', 'availability_365', 'number_of_reviews']]
var_dep=df['has_availability']

X=vars_indep
y=var_dep

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [27]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[    0    91]
 [    0 11000]]


In [31]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="t")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.9917951492200884


In [32]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.9917951492200884


In [34]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="t")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [4]:
df["host_response_time"] = df["host_response_time"].replace({
    "within an hour": 1,
    "within a few hours": 2,
    "within a day": 3,
    "a few days or more": 4,
    "SIN INFORMACION": 5
})

# Verificar que la conversión fue correcta
print(df["host_response_time"].value_counts())

host_response_time
1    19227
2     6136
5     5068
3     3712
4     2824
Name: count, dtype: int64


C:\Users\angie\AppData\Local\Temp\ipykernel_20320\2354697535.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_response_time"] = df["host_response_time"].replace({


In [5]:
vars_indep=df[['maximum_nights', 'minimum_nights', 'host_response_time']]
var_dep=df['instant_bookable']

X=vars_indep
y=var_dep

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [7]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[8561    0]
 [2530    0]]


In [13]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="f")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.7718871156793797


In [14]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.7718871156793797


In [15]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [16]:
df["room_type"] = df["room_type"].replace({
    "Entire home/apt": 1,
    "Private room": 2,
    "Shared room": 3,
    "Hotel room": 4
})

print(df["room_type"].value_counts())

room_type
1    29079
2     7231
3      629
4       28
Name: count, dtype: int64


C:\Users\angie\AppData\Local\Temp\ipykernel_20320\4175036345.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["room_type"] = df["room_type"].replace({


In [ ]:
df["bedrooms"] = df["bedrooms"].replace({
    0: "De 0 a 1 recamara",
    1: "De 0 a 1 recamara",
    1.4: "De 0 a 1 recamara",
    2: "De 2 a 3 recamaras",
    3: "De 2 a 3 recamaras"
})

# Verificar que la conversión fue correcta
print(df["bedrooms"].value_counts())

bedrooms
De 0 a 1 recamara    24401
De 2 a 3 camas       12566
Name: count, dtype: int64


In [19]:
vars_indep=df[['room_type', 'bathrooms', 'beds']]
var_dep=df['bedrooms']

X=vars_indep
y=var_dep

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['De 0 a 1 recamara', 'De 2 a 3 camas', 'De 0 a 1 recamara', ...,
       'De 0 a 1 recamara', 'De 0 a 1 recamara', 'De 0 a 1 recamara'],
      dtype=object)

In [21]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[6850  458]
 [1247 2536]]


In [23]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="De 0 a 1 recamara")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8459923428430283


In [24]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8462717518708863


In [25]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="De 0 a 1 recamara")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9373289545703338


In [27]:
df["minimum_nights"] = df["minimum_nights"].replace({
    1: "De 0 a 3 noches minimas",
    2: "De 0 a 3 noches minimas",
    2.2: "De 0 a 3 noches minimas",
    3: "De 0 a 3 noches minimas",
    4: "De 3 a 6 noches minimas",
    5: "De 3 a 6 noches minimas",
    6: "De 3 a 6 noches minimas"
})

# Verificar que la conversión fue correcta
print(df["minimum_nights"].value_counts())

minimum_nights
De 0 a 3 noches minimas    32399
De 3 a 6 noches minimas     4568
Name: count, dtype: int64


In [28]:
vars_indep=df[['price', 'room_type', 'availability_365']]
var_dep=df['minimum_nights']

X=vars_indep
y=var_dep

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)
escalar=StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred=algoritmo.predict(X_test)
y_pred

array(['De 0 a 3 noches minimas', 'De 0 a 3 noches minimas',
       'De 0 a 3 noches minimas', ..., 'De 0 a 3 noches minimas',
       'De 0 a 3 noches minimas', 'De 0 a 3 noches minimas'], dtype=object)

In [30]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

Matriz de confusion:
[[9649    0]
 [1442    0]]


In [32]:
from sklearn.metrics import precision_score

precision=precision_score(y_test, y_pred, average="binary", pos_label="De 0 a 3 noches minimas")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8699846722567848


In [33]:
from sklearn.metrics import accuracy_score

exactitud=accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8699846722567848


In [34]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="De 0 a 3 noches minimas")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0
